[WIP]メッセージの非同期通信化
emincoring/chat-space pull request #9
Opened 2019-04-02 08:09 UTC by emincoring

# WHAT
メッセージを非同期で送れるように編集する

# WHY
メッセージ送信機能の高速化のため。

2019-04-05 10:02 UTC, emincoring commented
画像キャプチャ
https://gyazo.com/b156af78d5d7110270cf57baaad913e6
https://gyazo.com/33a5c38117ba7124fe60c5a70f05b601
https://gyazo.com/d468bb2c9cfa839e7339981e31ed7b44

2019-04-05 10:12 UTC, kohei-isoda commented on app/assets/javascripts/message.js
> +                    <img class="message__image" src=${message.image.url}>
imageがもし無い時（文字だけを送った時）に画像のアイコンが出てしまっているので条件分岐して、画像がある時のHTML、無い時のHTMLを作成しましょう！

2019-04-05 10:20 UTC, emincoring commented on app/assets/javascripts/message.js
> +                    <img class="message__image" src=${message.image.url}>
その条件分岐する方法が分からず、先ほどコネクトで質問したのですが、後々条件分岐するカリキュラムが出てくるので今は条件分岐なしのこのままで良いと言われました。。

2019-04-05 10:48 UTC, kohei-isoda commented on app/assets/javascripts/message.js
> +                    <img class="message__image" src=${message.image.url}>
大変遅くなってしまい申し訳ございません！

只今担当者に確認させて頂きましたが、
「if文なしで非同期で送れるようにしてもらった後、if文の実装をしましょう」
とお伝えさせていただいたそうですが、赤木さんのご認識と相違ないでしょうか？

まとめると、弊社の認識ではこのPull Requestをマージする前のタイミングで
条件分岐を実装して頂きたいということになります！宜しくお願い致します。


礒田

2019-04-06 09:03 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +                    <img class="message__image" src=${message.image.url}>
こちらは、imageHTMLという変数を定義し、imageがある時、`imageHTML = <img class="message__image" src=${message.image.url}>`、imageがない時は空文字を代入するように三項演算子を使って定義し、ここで`${imageHTML}`と呼び出しましょう！

2019-04-06 11:01 UTC, emincoring commented on app/assets/javascripts/message.js
> +                    <img class="message__image" src=${message.image.url}>
> こちらは、imageHTMLという変数を定義し、imageがある時、`imageHTML = <img class="message__image" src=${message.image.url}>`、imageがない時は空文字を代入するように三項演算子を使って定義し、ここで`${imageHTML}`と呼び出しましょう！

こちら試してみましたが、画像のような表示になってしまいます。
https://gyazo.com/e4188fdbb1c95117cc23571e3550eee1

コネクトで質問しましたが解決しませんでした。。
kutokoさんの思っているコードではないのでしょうか？

私の書いたコードは下記です。

  function buildHTML(message){
    var imageHTML = message.image ? `<img class="message__image" src=${message.image.url}>` : '';

    // var image = message.image.url ? message.image.url : '';
    var html = `<div class="message">
                  <div class="message__info">
                    <p class="message__info__user">
                      ${message.user_name}
                    </p>
                    <p class="message__info__date">
                      ${message.time}
                    </p>
                  </div>
                  <p class="message__text">
                    <p class="message__text__content">
                      ${message.content}
                    </p>
                    ${imageHTML}
                  </p>
                </div>`;
    return html;
  }

2019-04-06 11:20 UTC, kuroko918 reviewed
一度こちらで試してみてください。

2019-04-06 11:20 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
この行の下に
```
imageHTML = (message.image) ? `<img class="message__image" src=${message.image.url}>` :  ""
```
と書いてください。

2019-04-06 11:20 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +                    <img class="message__image" src=${message.image.url}>
ここの行を
`${imageHTML}`
と変更してください。

2019-04-07 09:22 UTC, emincoring commented on app/assets/javascripts/message.js
> +                    <img class="message__image" src=${message.image.url}>
ご教授いただきありがとうございます。そのように記入していますが、同様の状況です。。
https://gyazo.com/e69625acabc8ac51ef780620611b3b7b

2019-04-07 09:34 UTC, yuki-uchida requested changes

2019-04-07 09:34 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
なんのHTMLをbuildするのかわかる名前だと良いです

2019-04-07 09:34 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){
dataよりも具体的な名前で。

2019-04-07 10:13 UTC, hiroki5123 commented
pushしていただきますよう、お願い致します。

2019-04-07 10:13 UTC, emincoring commented on app/assets/javascripts/message.js
> +    .done(function(data){
名前変えました

2019-04-07 10:14 UTC, emincoring commented
すみませんpushしました

2019-04-07 10:14 UTC, emincoring commented
最終課題本日から始まってしまっているのでなるべく早く次に進みたいのでよろしくお願いします

2019-04-07 10:51 UTC, emincoring commented on app/assets/javascripts/message.js
> +      })
imageHTML = <img class="message__image" src=${message.image.url}>
を定義しても、imageがない場合でもimgタグが生成されてしまうので、
上記方法でimgタグを消す方法にしました。

2019-04-07 10:57 UTC, yuki-uchida requested changes

2019-04-07 10:57 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +                    <img class="message__image" src=${message.image.url}>
こちら、エラーメッセージが404notfoundとなっており、特定のURLにアクセスしたが、アクセスできないというエラーになります。
つまり、エラーが起きているのはここのコードではなく、ajaxの部分になります。
ajaxが成功した時にはdone(~~~){
}の方に飛びますので、こちらの中でconsole.log("success!!")と書きましょう。

そうすればそもそもajaxが成功していないことがわかると思われます

2019-04-07 11:22 UTC, emincoring commented
console.logで確認しましたがajaxは飛んでいます。
https://gyazo.com/9788c0f420b6dd052f0cc75560c7e06b
恐らく、srcがnullになって送られてしまっていてエラーが出ますが、
$('img').error(function(){
          $(this).remove();
        });
でimgタグを削除するようにしているので問題ないかと思うのですがいかがでしょうか？

2019-04-07 11:35 UTC, yuki-uchida commented
失礼致しました。
srcがない事が原因ですね。

今回のエラーを解決するためにimgタグを消すというのは正しい方法です。
ただ、よりスマートな方法としては、${imageHTML}のimageHTMLを、URLにするのではなく、imgタグ全体にすると良いです。

<img src="${imageHTML}">ではsrcがないため、今回のような表示になってしまいますが、
var imageHTML = image.url :"<img src='〜〜'>？ ""
とすることで、imageがない時にそもそもimgタグがないことに出来ます

2019-04-07 11:59 UTC, ghost requested changes

2019-04-07 11:59 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      // $('img').error(function(){
コメントアウトするのであれば削除してください

2019-04-07 12:10 UTC, emincoring commented
画像表示できない表示が出ちゃうので、コメントアウト解除してコードを反映しました。

ライフコーチに相談し、次に進めないとなのでここで一旦マージします。

2019-04-07 12:11 UTC, merged